server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10MB # 요청한 파일 한 개의 최대 크기
      max-request-size: 10MB # 요청한 파일 전체의 최대 크기

  jpa:
    open-in-view: false
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl #camelCase to lower_snake_case
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 500

management:
  endpoints:
    web:
      base-path: /api
      path-mapping:
        health: health
  endpoint:
    health:
      show-details: never
  health:
    elasticsearch:
      enabled: false

--- #dev
logging:
  level:
    com: debug
    org.hibernate.type: off # 바인딩 할 값을 찍는 로그

webclient:
#  baseurl: http://localhost
  baseurl: http://whizzle.o-r.kr

spring:
  config:
    activate:
      on-profile: "global-dev"
  devtools:
    livereload:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 500

--- #prod
logging:
  level:
    com: info

webclient:
  baseurl: http://whizzle.o-r.kr

spring:
  config:
    activate:
      on-profile: "global-prod"